language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "pollen-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy:
  - rm -rf node_modules # omit from the tarball, since we skip cleanup

deploy:
  on: 
    all branches: true
  env:
    secure: "qRbs+4Xb8auaIO65QNBkWWCt/y8AbFR0pRiH7qeadpvxpLh9LDZLR3cZ/tfI2zXdst36lUIatUdmH2W/vjlRjndUYC3sCsQgPPcN5Z1/JLKDn5NK2Z1mn8Jr/DmjYot5hjo/GSyfyYFzHq4+eLeq/r18Px+C5mMugCD1zlCmLqNzj/YrhcDb4XsjWh4rQu8lYRCGOZ78b/jyMLr3fQXybTKiJDBecOwKsdOT5cS0b/XoH7p9w50j02JN4Dih7Yjgd80o8UdS9dFmF3iq64DSQK7CK3k76eWI9dTuELeG8qHkph7s501cdaigfrMIqkZTP89Otvl9/ViTM+q9TwV9xL0QVtEfKGUwuFdOzwR7ftbYam+bJhyY+cdFa0sHR8oS69JGssggUUdNlo8v0cAgZpoUEZSDIPUAZk5rZmvYV12KLJpsGNZd56EyFMuSRraWufOu99IWqldUX2JRb7OvKPJ4+f6l9SkO4WBPlK7Cdf0IB+yYx3nuJOr0RYuU+CjLL7/acPROnAeJKOp6tTbL3hqXj2xc9vGu6y4w/hGgbPgP/7mjq9ZUdNkAypsOGSQeE4k1Yc6ECrmtRv4Pi9X273JyHQICbIAF3C3zod9Qwxo/h9jdSSnwy+QUjO8dUA0rG70Jz/fIOm5TIJTedRGuTYkPbKKfwVqsvdrEy9mffa8="
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: pollen-the-garden
  api_key:
    secure: c+l/6hwg1sKzudeasI3W+RapO+D9ABP9d6sr+lCaKKD6nWoGY9NGCr5HQy7eH5tnFKr8Xq5zluwNjODnl16C0/rP/ma8NNH7w/jz9Vqt1wonTBzBpuON9XXjOm4jqPSHHLy3UM42dyMl/1OoDhrYSRuY0CN04zVuTMHVcJxy2S9rMyaAEiZrTVzHp/g1PPhvSofNWbaUEjat6pZ07+AtgHxGwD9JpsGA0yZl1b3AyV3vqkqoyZxhfljCJ84cd3vXW8pEVHOTK6tLvo/uld/yq8/K6bIn6Sejkr9c4jusxHLs5My4HHuX9MFBVbNop1DakIwCNMDAfCTFTuisVlZ2RB1DAdHkaZXtTxBFSjO03fomLd842aDHL4F/1ME2Df64fTWy+74/YzlGW62T6gl9SXb1Qnusm5x/jCgzWHNe9cb6yAMFnPco15vwy92eNBSD/p0irmNnVAJcBrqu5Iuf/pnYFAotcZxOMC5y2PTrX7e/TAOfSRhsXz+cVGXmFKBOIW6oX7rCNHu+Lm56Ck5qC1wpvY5v4v/PKO1GTN3XTqO5srvi1MXjFfu90vcKf+5/dGDj9M3HQUMMJGhTLLhqBJRoCVURzAeh4RSzxNl6wOS5zwbLN+PV0GD7/u1xlB3jMQg4ycCADUnpT30PdgsIs7dCf+/4Rg3VyY1Igd8HUY8=

